=== mastif/mastif-original/med_facts_xml_project/src/main/resources/rules_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.mitre.org/medfacts"
    xmlns:m="http://www.mitre.org/medfacts"
    xmlns="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">



    <complexType name="ClassType">
    	<sequence>
    		<element ref="m:class-name" maxOccurs="1" minOccurs="1"></element>
    		<element ref="m:class-value" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <simpleType name="ClassNameType">
    	<restriction base="string"></restriction>
    </simpleType>

    <simpleType name="ClassValueType">
    	<restriction base="string"></restriction>
    </simpleType>

    <element name="class-name" type="m:ClassNameType"></element>

    <element name="class-value" type="m:ClassValueType"></element>

    <element name="class" type="m:ClassType"></element>

    <complexType name="ConfigurationType">
    	<sequence>
    		<element ref="m:class" maxOccurs="unbounded" minOccurs="0"></element>
    		<element ref="m:rule" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <element name="rule" type="m:RuleType"></element>

    <element name="configuration" type="m:ConfigurationType"></element>
    <simpleType name="TagTypeOld">
        <restriction base="xsd:string">
            <enumeration value="PREN">
                <annotation>
                    <documentation>pre-negation</documentation>
                </annotation>
            </enumeration>
            <enumeration value="POST">
                <annotation>
                    <documentation>post-negation</documentation>
                </annotation>
            </enumeration>
            <enumeration value="PREP">
                <annotation>
                    <documentation>pre-possible</documentation>
                </annotation>
            </enumeration>
            <enumeration value="POSP">
                <annotation>
                    <documentation>post-possible</documentation>
                </annotation>
            </enumeration>
            <enumeration value="PSEU">
                <annotation>
                    <documentation>pseudo-negation</documentation>
                </annotation>
            </enumeration>
            <enumeration value="CONJ">
                <annotation>
                    <documentation>conjunciton</documentation>
                </annotation>
            </enumeration>
        </restriction>
    </simpleType>
    <element name="tag" type="m:TagTypeOld"></element>
    <complexType name="RuleType">
        <simpleContent>
            <extension base="m:RuleStringType">
                <attribute name="tag" type="m:TagTypeOld" use="required"/>
            </extension>
        </simpleContent>
    </complexType>
    <simpleType name="RuleStringType">
        <restriction base="xsd:string">
            <whiteSpace value="preserve"/>
            <pattern value=".+"/>
        </restriction>
    </simpleType>
    <simpleType name="DirectionType">
        <restriction base="xsd:string">
            <enumeration value="pre"/>
            <enumeration value="post"/>
        </restriction>
    </simpleType>
    <simpleType name="TagType">
        <restriction base="xsd:string">
            <enumeration value="negation"/>
            <enumeration value="possibility"/>
            <enumeration value="pseudo"/>
            <enumeration value="conjunction"/>
        </restriction>
    </simpleType>
</schema>

=== mastif/mastif-original/med_facts_xml_project/src/main/resources/rules_sample_09a.xml
<?xml version="1.0" encoding="UTF-8"?>
<m:configuration  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:m='http://www.mitre.org/medfacts'
   xsi:schemaLocation='http://www.mitre.org/medfacts rules_schema.xsd'>
    <m:class m:id="patient_ref">
        <!--<m:class-name>patient_ref</m:class-name>-->
        <m:class-value>the patient</m:class-value>
        <m:class-value>him</m:class-value>
        <m:class-value>her</m:class-value>
        <m:class-value />
    </m:class>
    <m:class m:id="direction_ref">
        <!--<m:class-name>direction_ref</m:class-name>-->
        <m:class-value>for</m:class-value>
        <m:class-value>against</m:class-value>
        <m:class-value />
    </m:class>
    <m:rule tag="negation" direction="pre">rules <m:class-ref idref="patient_ref"/> out</m:rule>
    <!-- <m:rule m:id="rule_out_ref" tag="negation" direction="pre">rule <m:class-ref idref="patient_ref"/> out</m:rule> -->
    <!-- <m:rule tag="negation" direction="pre">did <m:rule-ref idref="rule_out_ref"/> <m:class-ref idref="direction_ref"/></m:rule> -->

    <!--
    <m:rule tag="PREN">did ${rule_out}</m:rule>
    <m:rule tag="PREN">did ${rule_out} for</m:rule>
    <m:rule tag="PREN">did ${rule_out} against</m:rule>
    <m:rule tag="PREN">can ${rule_out}</m:rule>
    <m:rule tag="PREN">can ${rule_out} for</m:rule>
    <m:rule tag="PREN">can ${rule_out} against</m:rule>
    -->
</m:configuration>

=== mastif/mastif-original/med_facts_xml_project/src/main/resources/rules_sample_09.xml
<?xml version="1.0" encoding="UTF-8"?>
<m:configuration  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:m='http://www.mitre.org/medfacts'
   xsi:schemaLocation='http://www.mitre.org/medfacts rules_schema.xsd'>
    <m:class>
        <m:class-name>patient_ref</m:class-name>
        <m:class-value>the patient</m:class-value>
        <m:class-value>him</m:class-value>
        <m:class-value>her</m:class-value>
        <m:class-value />
    </m:class>
    <m:class>
        <m:class-name>direction_ref</m:class-name>
        <m:class-value>for</m:class-value>
        <m:class-value>against</m:class-value>
        <m:class-value />
    </m:class>
    <m:rule tag="PREN">rules <class-ref idref="patient_ref"/> out</m:rule>
    <m:rule name="rule_out" tag="PREN">rule <class-ref idref="patient_ref"/> out</m:rule>
    <m:rule tag="PREN">did <class-ref idref="rule_out_ref"/> <class-ref idref="direction_ref"/></m:rule>

    <!--
    <m:rule tag="PREN">did ${rule_out}</m:rule>
    <m:rule tag="PREN">did ${rule_out} for</m:rule>
    <m:rule tag="PREN">did ${rule_out} against</m:rule>
    <m:rule tag="PREN">can ${rule_out}</m:rule>
    <m:rule tag="PREN">can ${rule_out} for</m:rule>
    <m:rule tag="PREN">can ${rule_out} against</m:rule>
    --%>
</m:configuration>

=== mastif/mastif-original/med_facts_xml_project/src/main/resources/rules_sample_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns='http://www.mitre.org/medfacts'
   xsi:schemaLocation='http://www.mitre.org/medfacts rules_schema.xsd'>
    <class>
        <class-name>patient_ref</class-name>
        <class-value>the patient</class-value>
        <class-value>him</class-value>
        <class-value>her</class-value>
        <class-value />
    </class>
    <class>
        <class-name>direction_ref</class-name>
        <class-value>for</class-value>
        <class-value>against</class-value>
        <class-value />
    </class>
    <rule name="rule_out" tag="PREN">rule ${patient_ref} out</rule>
    <rule tag="PREN">did ${rule_out} ${direction_ref}</rule>
</configuration>
